name: delete the branch when PR is closed

on: workflow_dispatch

jobs:
  delete-branch-when-pr-closed:
    runs-on: ubuntu-latest
    if: ${{ github.base_ref == 'master' }}
    steps:
      - name: delete branch
        uses: SvanBoxel/delete-merged-branch@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
